[package]
name = "city_generator"
version = "0.1.0"
authors = ["coffee"]

[dependencies]
# SerDe (Serialize/deserialize)
serde = "1.0.60"
serde_json = "1.0.17"
serde_derive = "1.0.60"

# Random
rand = "0.5.0"

# The new error standard, "Failure"
failure = "0.1.1"
failure_derive = "0.1.1"